name: EAS

on:
  push:
    branches: [main]
  pull_request:
    types: labeled
  workflow_dispatch:

jobs:
  eas:
    uses: DleanJeans/expo-workflows/.github/workflows/eas.yml@main
    with:
      app-name: recupero
      expo-project-slug: recupero
      ota-push-branch: preview
      ota-label: send ota
    secrets:
      expo-token: ${{ secrets.EXPO_TOKEN }}
